// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcu99tnwu8XsHT8EhvbJSTyy_-cJh1eK0',
    appId: '1:166028945866:web:39ed40991e329cd3980733',
    messagingSenderId: '166028945866',
    projectId: 'gooddeal-app',
    authDomain: 'gooddeal-app.firebaseapp.com',
    storageBucket: 'gooddeal-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDVaxfUfGISyUzgbdnXkYWlj3QcX4Kr3Y',
    appId: '1:166028945866:android:1ad76354ce4415a1980733',
    messagingSenderId: '166028945866',
    projectId: 'gooddeal-app',
    storageBucket: 'gooddeal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5Cn5F5zaRlZ9yBACBfvLRm-rmd3-OFA',
    appId: '1:166028945866:ios:d5cdf1a258be846f980733',
    messagingSenderId: '166028945866',
    projectId: 'gooddeal-app',
    storageBucket: 'gooddeal-app.firebasestorage.app',
    iosBundleId: 'com.gooddeal.app',
  );
}
